SELECT COUNT(*) AS groups,
       SUM(CASE WHEN c>1 THEN 1 ELSE 0 END) AS non_unique_groups
FROM (
  SELECT
    CAST(LVL1_ACCT_GID AS STRING),
    CAST(LVL3_ACCT_GID AS STRING),
    CAST(MBR_ACCT_ID AS STRING),
    CAST(FILL_DT AS STRING),
    CAST(FRMLY_NDC_EFF_DT AS STRING),
    CAST(FRMLY_NDC_EXPRN_DT AS STRING),
    CAST(SRC_FRMLY_PDL_CD AS STRING),
    CAST(SRC_CD AS STRING),
    COUNT(*) c
  FROM `...sdl.T_NON_FRMLY_MEDD_QL`
  WHERE FILL_DT BETWEEN DATE_TRUNC(DATE_SUB(CURRENT_DATE('America/Phoenix'), INTERVAL 39 MONTH), MONTH)
                    AND DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Phoenix'), MONTH), INTERVAL 1 DAY)
  GROUP BY 1,2,3,4,5,6,7,8
);
